version: "3.9"
services:
    app:
        build: .
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            VIRTUAL_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_HOST: ${HOST_DOMAIN}
            CONFIG_PATH: ${CONFIG_PATH}
            HTTP_SERVER_PASSWORD: ${HTTP_SERVER_PASSWORD}
